name: Run EditMode and PlayMode Test
on:
  workflow_dispatch: {}
jobs:
  test:
    name: Run EditMode and PlayMode Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out my unity project.
        uses: actions/checkout@v4

      - name: Run EditMode and PlayMode Test
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

        with:
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}

          unityVersion: 2022.3.13f1

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts
